[package]
name = "mpass"
version = "0.4.1"
authors = ["Daniil Smirnov <danslapman@gmail.com>"]

[dependencies]
clap = "2.20"
rust-crypto = "^0.2"
rustc-serialize = "0.3"
bincode = "0.6"
yaml-rust = "0.3"
rand = "0.3"
mdo = "^0.3"
serde = "0.8.*"
serde_json = "0.8.*"
serde_derive = "0.8.*"