[package]
name = "mpass"
version = "0.3.0"
authors = ["Daniil Smirnov <danslapman@gmail.com>"]

[dependencies]
clap = "2.20"
rust-crypto = "^0.2"
rustc-serialize = "0.3"
bincode = "0.6"
yaml-rust = "0.3"
rand = "0.3"
mdo = "^0.3"